# Generated by Django 3.1.4 on 2020-12-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='message',
        ),
    ]
